---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())
library("dplyr")
library("data.table")
library("tsDyn")
library("sparsevar")

FILE_PATH <- getwd()

source(file.path(FILE_PATH, "utils", "Rutils.R"))
```

```{r}
P <- 1
T <- 100
K <- 150
seed <- 02021994
prob <- 0.1
network <- "random"

var_sim <- simulateVAR(N = K, p = P, nobs = T, sparsity=prob)
ts_dgp_df <- var_sim$series %>% as.data.table()
B <- var_sim$A[[1]]

ts.plot(ts_dgp_df, col=c(1:K))
```

```{r}
beta <- B %>% as.data.table()
colnames(beta) <- gsub("V", "", colnames(beta))
dgp_data <- ts_dgp_df %>% as.data.table()
corr_dgp <- cov_combination_2x2(data = dgp_data, p = P)

betas_dgp <- beta %>% mutate(eq = row.names(beta)) %>% dplyr::select(eq, everything())
y_dgp <- melt(betas_dgp, id = c("eq")) %>% as.data.table() %>%
  rename(betas_dgp = value) %>% mutate(eq = as.chsaracter(eq), variable=as.character(variable))

betas_corr_df <- cbind(y_dgp %>% dplyr::select(betas_dgp), corr_dgp %>% dplyr::select(beta_estimate)) %>% as.data.table()
plot(x = betas_corr_df$beta_estimate,
     y = betas_corr_df$betas_dgp,
     ylab = "True phi's",
     xlab = "Proxy phi's (reg. betas 2x2)",
     main = "True parameters of the VAR(1) model vs a proxy (k=150, T=100)")
```


```{r}
betas_corr_no_zero_df <- betas_corr_df %>% filter(betas_dgp != 0)
plot(x = betas_corr_no_zero_df$beta_estimate,
     y = betas_corr_no_zero_df$betas_dgp,
     ylab = "True phi's",
     xlab = "Proxy phi's (covariance)",
     main = "True parameters (excluding phi=0) of the VAR(1) \n model vs a proxy (k=150, T=100)")
```

```{r}
betas_corr_no_zero_df <- betas_corr_df %>% filter((betas_dgp != 0)&(betas_dgp > 0))
plot(x = betas_corr_no_zero_df$beta_estimate,
     y = betas_corr_no_zero_df$betas_dgp,
     ylab = "True phi's",
     xlab = "Proxy phi's (covariance)",
     main = "True parameters (phi > 0) of the VAR(1) \n model vs a proxy (k=150, T=100)")
```

```{r}
betas_corr_no_zero_positive_df <- betas_corr_df %>% filter((betas_dgp != 0)&(betas_dgp < 0))
plot(x = betas_corr_no_zero_positive_df$beta_estimate,
     y = betas_corr_no_zero_positive_df$betas_dgp,
     ylab = "True phi's",
     xlab = "Proxy phi's (covariance)",
     main = "True parameters (phi < 0) of the VAR(1) \n model vs a proxy (k=150, T=100)")
```










